### PR TITLE
Change url to open local discord client instead

### PR DESCRIPTION
**Pull request by moka491**
This PR allows the website to instead open the user's locally installed client upon clicking the button.
I think users are much more likely to use discord on their systems vs in the browser (where they usually have to login first before adding the user).

### CODE REVIEW

**Comment by taichikuji** [comment]
I like it! However, few things to point out.

1- Even if it currently works on my device, I don't like the timeout you added to fallback onto the url if it fails. Can you figure out a way to reliably do this?

2- I would appreciate this being as straight forward as possible. If a check has to be added, so be it, but if it can be evaded, I'd prefer it being not added in.

3- I'm not sure, since I didn't do my research yet, and will notify later, but maybe there's a way to trigger the discord:// protocol on android the same way it behaves on desktop. Can you try to research this as well?

Once again, thank you very much for the PR! Let's try to get this onto the project, I think it's going to be a great addition once we get these things ironed out!

**Comment by moka491** [comment]
I've now added a dedicated mobile device check that makes use of the new browser client hints feature (https://medium.com/fiverr-engineering/detect-mobile-browsers-without-user-agent-string-parsing-66e3694ce8cd)
on every supported device (https://caniuse.com/mdn-api_navigator_useragentdata) and only falls back to a catch-all user agent check on browsers that don't support it (basically only Firefox).
Once Firefox supports this, you can even remove the user agent check completely.

Let us test this and see 👍

**Review by taichikuji — APPROVED** [review]

**Comment by moka491** [comment]
I tested the changes on the netlify deploy preview.
On desktop, as well as on Firefox Mobile, Brave Mobile and Opera Mobile, the behavior is as expected and the same as on the currently deployed version 👍

**Comment by taichikuji** [comment]
Will commit changes to the dev branch, then make necessary changes and then push to master. Once again, thank you very much for your PR! Will close it now.

**Pull request merged**
